apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-278
  namespace: pki-tenant-large-tier-19
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-app-278
  template:
    metadata:
      labels:
        app: workload-app-278
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-279
  namespace: pki-tenant-large-tier-19
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-app-279
  template:
    metadata:
      labels:
        app: workload-app-279
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-280
  namespace: pki-tenant-large-tier-19
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-app-280
  template:
    metadata:
      labels:
        app: workload-app-280
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-281
  namespace: pki-tenant-large-tier-19
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-app-281
  template:
    metadata:
      labels:
        app: workload-app-281
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-282
  namespace: pki-tenant-large-tier-19
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-app-282
  template:
    metadata:
      labels:
        app: workload-app-282
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-283
  namespace: pki-tenant-large-tier-19
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-app-283
  template:
    metadata:
      labels:
        app: workload-app-283
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-284
  namespace: pki-tenant-large-tier-19
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-app-284
  template:
    metadata:
      labels:
        app: workload-app-284
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-285
  namespace: pki-tenant-large-tier-19
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-app-285
  template:
    metadata:
      labels:
        app: workload-app-285
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-286
  namespace: pki-tenant-large-tier-19
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-app-286
  template:
    metadata:
      labels:
        app: workload-app-286
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-287
  namespace: pki-tenant-large-tier-19
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-app-287
  template:
    metadata:
      labels:
        app: workload-app-287
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-288
  namespace: pki-tenant-large-tier-19
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-app-288
  template:
    metadata:
      labels:
        app: workload-app-288
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-289
  namespace: pki-tenant-large-tier-19
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-app-289
  template:
    metadata:
      labels:
        app: workload-app-289
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-290
  namespace: pki-tenant-large-tier-19
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-app-290
  template:
    metadata:
      labels:
        app: workload-app-290
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-291
  namespace: pki-tenant-large-tier-19
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-app-291
  template:
    metadata:
      labels:
        app: workload-app-291
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-292
  namespace: pki-tenant-large-tier-19
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-app-292
  template:
    metadata:
      labels:
        app: workload-app-292
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
