apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-65
  namespace: pki-tenant-large-tier-5
spec:
  replicas: 19
  selector:
    matchLabels:
      app: workload-app-65
  template:
    metadata:
      labels:
        app: workload-app-65
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "128Mi"
          requests:
            cpu: "50m"
            memory: "64Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-66
  namespace: pki-tenant-large-tier-5
spec:
  replicas: 19
  selector:
    matchLabels:
      app: workload-app-66
  template:
    metadata:
      labels:
        app: workload-app-66
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "128Mi"
          requests:
            cpu: "50m"
            memory: "64Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-67
  namespace: pki-tenant-large-tier-5
spec:
  replicas: 19
  selector:
    matchLabels:
      app: workload-app-67
  template:
    metadata:
      labels:
        app: workload-app-67
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "128Mi"
          requests:
            cpu: "50m"
            memory: "64Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-68
  namespace: pki-tenant-large-tier-5
spec:
  replicas: 19
  selector:
    matchLabels:
      app: workload-app-68
  template:
    metadata:
      labels:
        app: workload-app-68
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "128Mi"
          requests:
            cpu: "50m"
            memory: "64Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-69
  namespace: pki-tenant-large-tier-5
spec:
  replicas: 19
  selector:
    matchLabels:
      app: workload-app-69
  template:
    metadata:
      labels:
        app: workload-app-69
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "128Mi"
          requests:
            cpu: "50m"
            memory: "64Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-70
  namespace: pki-tenant-large-tier-5
spec:
  replicas: 19
  selector:
    matchLabels:
      app: workload-app-70
  template:
    metadata:
      labels:
        app: workload-app-70
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "128Mi"
          requests:
            cpu: "50m"
            memory: "64Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-71
  namespace: pki-tenant-large-tier-5
spec:
  replicas: 19
  selector:
    matchLabels:
      app: workload-app-71
  template:
    metadata:
      labels:
        app: workload-app-71
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "128Mi"
          requests:
            cpu: "50m"
            memory: "64Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-72
  namespace: pki-tenant-large-tier-5
spec:
  replicas: 19
  selector:
    matchLabels:
      app: workload-app-72
  template:
    metadata:
      labels:
        app: workload-app-72
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "128Mi"
          requests:
            cpu: "50m"
            memory: "64Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-73
  namespace: pki-tenant-large-tier-5
spec:
  replicas: 19
  selector:
    matchLabels:
      app: workload-app-73
  template:
    metadata:
      labels:
        app: workload-app-73
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "128Mi"
          requests:
            cpu: "50m"
            memory: "64Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-74
  namespace: pki-tenant-large-tier-5
spec:
  replicas: 19
  selector:
    matchLabels:
      app: workload-app-74
  template:
    metadata:
      labels:
        app: workload-app-74
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "128Mi"
          requests:
            cpu: "50m"
            memory: "64Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-75
  namespace: pki-tenant-large-tier-5
spec:
  replicas: 19
  selector:
    matchLabels:
      app: workload-app-75
  template:
    metadata:
      labels:
        app: workload-app-75
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "128Mi"
          requests:
            cpu: "50m"
            memory: "64Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-76
  namespace: pki-tenant-large-tier-5
spec:
  replicas: 19
  selector:
    matchLabels:
      app: workload-app-76
  template:
    metadata:
      labels:
        app: workload-app-76
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "128Mi"
          requests:
            cpu: "50m"
            memory: "64Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-77
  namespace: pki-tenant-large-tier-5
spec:
  replicas: 19
  selector:
    matchLabels:
      app: workload-app-77
  template:
    metadata:
      labels:
        app: workload-app-77
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "128Mi"
          requests:
            cpu: "50m"
            memory: "64Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-78
  namespace: pki-tenant-large-tier-5
spec:
  replicas: 19
  selector:
    matchLabels:
      app: workload-app-78
  template:
    metadata:
      labels:
        app: workload-app-78
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "128Mi"
          requests:
            cpu: "50m"
            memory: "64Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-79
  namespace: pki-tenant-large-tier-5
spec:
  replicas: 19
  selector:
    matchLabels:
      app: workload-app-79
  template:
    metadata:
      labels:
        app: workload-app-79
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "128Mi"
          requests:
            cpu: "50m"
            memory: "64Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-80
  namespace: pki-tenant-large-tier-5
spec:
  replicas: 19
  selector:
    matchLabels:
      app: workload-app-80
  template:
    metadata:
      labels:
        app: workload-app-80
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "128Mi"
          requests:
            cpu: "50m"
            memory: "64Mi"
---
