apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-1
  namespace: pki-tenant-small-tier-1
spec:
  replicas: 6
  selector:
    matchLabels:
      app: workload-app-1
  template:
    metadata:
      labels:
        app: workload-app-1
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-2
  namespace: pki-tenant-small-tier-1
spec:
  replicas: 6
  selector:
    matchLabels:
      app: workload-app-2
  template:
    metadata:
      labels:
        app: workload-app-2
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-3
  namespace: pki-tenant-small-tier-1
spec:
  replicas: 6
  selector:
    matchLabels:
      app: workload-app-3
  template:
    metadata:
      labels:
        app: workload-app-3
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-4
  namespace: pki-tenant-small-tier-1
spec:
  replicas: 6
  selector:
    matchLabels:
      app: workload-app-4
  template:
    metadata:
      labels:
        app: workload-app-4
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-5
  namespace: pki-tenant-small-tier-1
spec:
  replicas: 6
  selector:
    matchLabels:
      app: workload-app-5
  template:
    metadata:
      labels:
        app: workload-app-5
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
