apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-323
  namespace: pki-tenant-large-tier-22
spec:
  replicas: 19
  selector:
    matchLabels:
      app: workload-app-323
  template:
    metadata:
      labels:
        app: workload-app-323
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-324
  namespace: pki-tenant-large-tier-22
spec:
  replicas: 19
  selector:
    matchLabels:
      app: workload-app-324
  template:
    metadata:
      labels:
        app: workload-app-324
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-325
  namespace: pki-tenant-large-tier-22
spec:
  replicas: 19
  selector:
    matchLabels:
      app: workload-app-325
  template:
    metadata:
      labels:
        app: workload-app-325
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-326
  namespace: pki-tenant-large-tier-22
spec:
  replicas: 19
  selector:
    matchLabels:
      app: workload-app-326
  template:
    metadata:
      labels:
        app: workload-app-326
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-327
  namespace: pki-tenant-large-tier-22
spec:
  replicas: 19
  selector:
    matchLabels:
      app: workload-app-327
  template:
    metadata:
      labels:
        app: workload-app-327
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-328
  namespace: pki-tenant-large-tier-22
spec:
  replicas: 19
  selector:
    matchLabels:
      app: workload-app-328
  template:
    metadata:
      labels:
        app: workload-app-328
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-329
  namespace: pki-tenant-large-tier-22
spec:
  replicas: 19
  selector:
    matchLabels:
      app: workload-app-329
  template:
    metadata:
      labels:
        app: workload-app-329
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-330
  namespace: pki-tenant-large-tier-22
spec:
  replicas: 19
  selector:
    matchLabels:
      app: workload-app-330
  template:
    metadata:
      labels:
        app: workload-app-330
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-331
  namespace: pki-tenant-large-tier-22
spec:
  replicas: 19
  selector:
    matchLabels:
      app: workload-app-331
  template:
    metadata:
      labels:
        app: workload-app-331
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-332
  namespace: pki-tenant-large-tier-22
spec:
  replicas: 19
  selector:
    matchLabels:
      app: workload-app-332
  template:
    metadata:
      labels:
        app: workload-app-332
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-333
  namespace: pki-tenant-large-tier-22
spec:
  replicas: 19
  selector:
    matchLabels:
      app: workload-app-333
  template:
    metadata:
      labels:
        app: workload-app-333
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-334
  namespace: pki-tenant-large-tier-22
spec:
  replicas: 19
  selector:
    matchLabels:
      app: workload-app-334
  template:
    metadata:
      labels:
        app: workload-app-334
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-335
  namespace: pki-tenant-large-tier-22
spec:
  replicas: 19
  selector:
    matchLabels:
      app: workload-app-335
  template:
    metadata:
      labels:
        app: workload-app-335
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-336
  namespace: pki-tenant-large-tier-22
spec:
  replicas: 19
  selector:
    matchLabels:
      app: workload-app-336
  template:
    metadata:
      labels:
        app: workload-app-336
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-337
  namespace: pki-tenant-large-tier-22
spec:
  replicas: 19
  selector:
    matchLabels:
      app: workload-app-337
  template:
    metadata:
      labels:
        app: workload-app-337
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
