apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-17
  namespace: pki-tenant-large-tier-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-app-17
  template:
    metadata:
      labels:
        app: workload-app-17
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "16Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-18
  namespace: pki-tenant-large-tier-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-app-18
  template:
    metadata:
      labels:
        app: workload-app-18
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "16Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-19
  namespace: pki-tenant-large-tier-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-app-19
  template:
    metadata:
      labels:
        app: workload-app-19
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "16Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-20
  namespace: pki-tenant-large-tier-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-app-20
  template:
    metadata:
      labels:
        app: workload-app-20
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "16Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-21
  namespace: pki-tenant-large-tier-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-app-21
  template:
    metadata:
      labels:
        app: workload-app-21
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "16Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-22
  namespace: pki-tenant-large-tier-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-app-22
  template:
    metadata:
      labels:
        app: workload-app-22
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "16Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-23
  namespace: pki-tenant-large-tier-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-app-23
  template:
    metadata:
      labels:
        app: workload-app-23
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "16Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-24
  namespace: pki-tenant-large-tier-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-app-24
  template:
    metadata:
      labels:
        app: workload-app-24
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "16Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-25
  namespace: pki-tenant-large-tier-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-app-25
  template:
    metadata:
      labels:
        app: workload-app-25
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "16Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-26
  namespace: pki-tenant-large-tier-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-app-26
  template:
    metadata:
      labels:
        app: workload-app-26
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "16Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-27
  namespace: pki-tenant-large-tier-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-app-27
  template:
    metadata:
      labels:
        app: workload-app-27
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "16Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-28
  namespace: pki-tenant-large-tier-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-app-28
  template:
    metadata:
      labels:
        app: workload-app-28
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "16Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-29
  namespace: pki-tenant-large-tier-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-app-29
  template:
    metadata:
      labels:
        app: workload-app-29
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "16Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-30
  namespace: pki-tenant-large-tier-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-app-30
  template:
    metadata:
      labels:
        app: workload-app-30
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "16Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-31
  namespace: pki-tenant-large-tier-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-app-31
  template:
    metadata:
      labels:
        app: workload-app-31
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "16Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-32
  namespace: pki-tenant-large-tier-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-app-32
  template:
    metadata:
      labels:
        app: workload-app-32
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "16Mi"
---
