apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-17
  namespace: pki-tenant-medium-tier-3
spec:
  replicas: 4
  selector:
    matchLabels:
      app: workload-app-17
  template:
    metadata:
      labels:
        app: workload-app-17
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-18
  namespace: pki-tenant-medium-tier-3
spec:
  replicas: 4
  selector:
    matchLabels:
      app: workload-app-18
  template:
    metadata:
      labels:
        app: workload-app-18
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-19
  namespace: pki-tenant-medium-tier-3
spec:
  replicas: 4
  selector:
    matchLabels:
      app: workload-app-19
  template:
    metadata:
      labels:
        app: workload-app-19
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-20
  namespace: pki-tenant-medium-tier-3
spec:
  replicas: 4
  selector:
    matchLabels:
      app: workload-app-20
  template:
    metadata:
      labels:
        app: workload-app-20
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-21
  namespace: pki-tenant-medium-tier-3
spec:
  replicas: 4
  selector:
    matchLabels:
      app: workload-app-21
  template:
    metadata:
      labels:
        app: workload-app-21
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-22
  namespace: pki-tenant-medium-tier-3
spec:
  replicas: 4
  selector:
    matchLabels:
      app: workload-app-22
  template:
    metadata:
      labels:
        app: workload-app-22
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-23
  namespace: pki-tenant-medium-tier-3
spec:
  replicas: 4
  selector:
    matchLabels:
      app: workload-app-23
  template:
    metadata:
      labels:
        app: workload-app-23
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
