apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-143
  namespace: pki-tenant-large-tier-10
spec:
  replicas: 19
  selector:
    matchLabels:
      app: workload-app-143
  template:
    metadata:
      labels:
        app: workload-app-143
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "128Mi"
          requests:
            cpu: "50m"
            memory: "64Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-144
  namespace: pki-tenant-large-tier-10
spec:
  replicas: 19
  selector:
    matchLabels:
      app: workload-app-144
  template:
    metadata:
      labels:
        app: workload-app-144
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "128Mi"
          requests:
            cpu: "50m"
            memory: "64Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-145
  namespace: pki-tenant-large-tier-10
spec:
  replicas: 19
  selector:
    matchLabels:
      app: workload-app-145
  template:
    metadata:
      labels:
        app: workload-app-145
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "128Mi"
          requests:
            cpu: "50m"
            memory: "64Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-146
  namespace: pki-tenant-large-tier-10
spec:
  replicas: 19
  selector:
    matchLabels:
      app: workload-app-146
  template:
    metadata:
      labels:
        app: workload-app-146
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "128Mi"
          requests:
            cpu: "50m"
            memory: "64Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-147
  namespace: pki-tenant-large-tier-10
spec:
  replicas: 19
  selector:
    matchLabels:
      app: workload-app-147
  template:
    metadata:
      labels:
        app: workload-app-147
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "128Mi"
          requests:
            cpu: "50m"
            memory: "64Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-148
  namespace: pki-tenant-large-tier-10
spec:
  replicas: 19
  selector:
    matchLabels:
      app: workload-app-148
  template:
    metadata:
      labels:
        app: workload-app-148
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "128Mi"
          requests:
            cpu: "50m"
            memory: "64Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-149
  namespace: pki-tenant-large-tier-10
spec:
  replicas: 19
  selector:
    matchLabels:
      app: workload-app-149
  template:
    metadata:
      labels:
        app: workload-app-149
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "128Mi"
          requests:
            cpu: "50m"
            memory: "64Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-150
  namespace: pki-tenant-large-tier-10
spec:
  replicas: 19
  selector:
    matchLabels:
      app: workload-app-150
  template:
    metadata:
      labels:
        app: workload-app-150
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "128Mi"
          requests:
            cpu: "50m"
            memory: "64Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-151
  namespace: pki-tenant-large-tier-10
spec:
  replicas: 19
  selector:
    matchLabels:
      app: workload-app-151
  template:
    metadata:
      labels:
        app: workload-app-151
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "128Mi"
          requests:
            cpu: "50m"
            memory: "64Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-152
  namespace: pki-tenant-large-tier-10
spec:
  replicas: 19
  selector:
    matchLabels:
      app: workload-app-152
  template:
    metadata:
      labels:
        app: workload-app-152
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "128Mi"
          requests:
            cpu: "50m"
            memory: "64Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-153
  namespace: pki-tenant-large-tier-10
spec:
  replicas: 19
  selector:
    matchLabels:
      app: workload-app-153
  template:
    metadata:
      labels:
        app: workload-app-153
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "128Mi"
          requests:
            cpu: "50m"
            memory: "64Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-154
  namespace: pki-tenant-large-tier-10
spec:
  replicas: 19
  selector:
    matchLabels:
      app: workload-app-154
  template:
    metadata:
      labels:
        app: workload-app-154
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "128Mi"
          requests:
            cpu: "50m"
            memory: "64Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-155
  namespace: pki-tenant-large-tier-10
spec:
  replicas: 19
  selector:
    matchLabels:
      app: workload-app-155
  template:
    metadata:
      labels:
        app: workload-app-155
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "128Mi"
          requests:
            cpu: "50m"
            memory: "64Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-156
  namespace: pki-tenant-large-tier-10
spec:
  replicas: 19
  selector:
    matchLabels:
      app: workload-app-156
  template:
    metadata:
      labels:
        app: workload-app-156
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "128Mi"
          requests:
            cpu: "50m"
            memory: "64Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-157
  namespace: pki-tenant-large-tier-10
spec:
  replicas: 19
  selector:
    matchLabels:
      app: workload-app-157
  template:
    metadata:
      labels:
        app: workload-app-157
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "128Mi"
          requests:
            cpu: "50m"
            memory: "64Mi"
---
