apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-173
  namespace: pki-tenant-large-tier-12
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-app-173
  template:
    metadata:
      labels:
        app: workload-app-173
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "16Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-174
  namespace: pki-tenant-large-tier-12
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-app-174
  template:
    metadata:
      labels:
        app: workload-app-174
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "16Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-175
  namespace: pki-tenant-large-tier-12
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-app-175
  template:
    metadata:
      labels:
        app: workload-app-175
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "16Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-176
  namespace: pki-tenant-large-tier-12
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-app-176
  template:
    metadata:
      labels:
        app: workload-app-176
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "16Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-177
  namespace: pki-tenant-large-tier-12
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-app-177
  template:
    metadata:
      labels:
        app: workload-app-177
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "16Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-178
  namespace: pki-tenant-large-tier-12
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-app-178
  template:
    metadata:
      labels:
        app: workload-app-178
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "16Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-179
  namespace: pki-tenant-large-tier-12
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-app-179
  template:
    metadata:
      labels:
        app: workload-app-179
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "16Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-180
  namespace: pki-tenant-large-tier-12
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-app-180
  template:
    metadata:
      labels:
        app: workload-app-180
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "16Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-181
  namespace: pki-tenant-large-tier-12
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-app-181
  template:
    metadata:
      labels:
        app: workload-app-181
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "16Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-182
  namespace: pki-tenant-large-tier-12
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-app-182
  template:
    metadata:
      labels:
        app: workload-app-182
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "16Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-183
  namespace: pki-tenant-large-tier-12
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-app-183
  template:
    metadata:
      labels:
        app: workload-app-183
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "16Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-184
  namespace: pki-tenant-large-tier-12
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-app-184
  template:
    metadata:
      labels:
        app: workload-app-184
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "16Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-185
  namespace: pki-tenant-large-tier-12
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-app-185
  template:
    metadata:
      labels:
        app: workload-app-185
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "16Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-186
  namespace: pki-tenant-large-tier-12
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-app-186
  template:
    metadata:
      labels:
        app: workload-app-186
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "16Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-187
  namespace: pki-tenant-large-tier-12
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-app-187
  template:
    metadata:
      labels:
        app: workload-app-187
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "16Mi"
---
