apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-128
  namespace: pki-tenant-large-tier-9
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-app-128
  template:
    metadata:
      labels:
        app: workload-app-128
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "16Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-129
  namespace: pki-tenant-large-tier-9
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-app-129
  template:
    metadata:
      labels:
        app: workload-app-129
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "16Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-130
  namespace: pki-tenant-large-tier-9
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-app-130
  template:
    metadata:
      labels:
        app: workload-app-130
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "16Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-131
  namespace: pki-tenant-large-tier-9
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-app-131
  template:
    metadata:
      labels:
        app: workload-app-131
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "16Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-132
  namespace: pki-tenant-large-tier-9
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-app-132
  template:
    metadata:
      labels:
        app: workload-app-132
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "16Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-133
  namespace: pki-tenant-large-tier-9
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-app-133
  template:
    metadata:
      labels:
        app: workload-app-133
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "16Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-134
  namespace: pki-tenant-large-tier-9
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-app-134
  template:
    metadata:
      labels:
        app: workload-app-134
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "16Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-135
  namespace: pki-tenant-large-tier-9
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-app-135
  template:
    metadata:
      labels:
        app: workload-app-135
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "16Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-136
  namespace: pki-tenant-large-tier-9
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-app-136
  template:
    metadata:
      labels:
        app: workload-app-136
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "16Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-137
  namespace: pki-tenant-large-tier-9
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-app-137
  template:
    metadata:
      labels:
        app: workload-app-137
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "16Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-138
  namespace: pki-tenant-large-tier-9
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-app-138
  template:
    metadata:
      labels:
        app: workload-app-138
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "16Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-139
  namespace: pki-tenant-large-tier-9
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-app-139
  template:
    metadata:
      labels:
        app: workload-app-139
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "16Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-140
  namespace: pki-tenant-large-tier-9
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-app-140
  template:
    metadata:
      labels:
        app: workload-app-140
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "16Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-141
  namespace: pki-tenant-large-tier-9
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-app-141
  template:
    metadata:
      labels:
        app: workload-app-141
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "16Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-142
  namespace: pki-tenant-large-tier-9
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-app-142
  template:
    metadata:
      labels:
        app: workload-app-142
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "16Mi"
---
