apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-203
  namespace: pki-tenant-large-tier-14
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-app-203
  template:
    metadata:
      labels:
        app: workload-app-203
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-204
  namespace: pki-tenant-large-tier-14
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-app-204
  template:
    metadata:
      labels:
        app: workload-app-204
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-205
  namespace: pki-tenant-large-tier-14
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-app-205
  template:
    metadata:
      labels:
        app: workload-app-205
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-206
  namespace: pki-tenant-large-tier-14
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-app-206
  template:
    metadata:
      labels:
        app: workload-app-206
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-207
  namespace: pki-tenant-large-tier-14
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-app-207
  template:
    metadata:
      labels:
        app: workload-app-207
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-208
  namespace: pki-tenant-large-tier-14
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-app-208
  template:
    metadata:
      labels:
        app: workload-app-208
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-209
  namespace: pki-tenant-large-tier-14
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-app-209
  template:
    metadata:
      labels:
        app: workload-app-209
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-210
  namespace: pki-tenant-large-tier-14
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-app-210
  template:
    metadata:
      labels:
        app: workload-app-210
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-211
  namespace: pki-tenant-large-tier-14
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-app-211
  template:
    metadata:
      labels:
        app: workload-app-211
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-212
  namespace: pki-tenant-large-tier-14
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-app-212
  template:
    metadata:
      labels:
        app: workload-app-212
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-213
  namespace: pki-tenant-large-tier-14
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-app-213
  template:
    metadata:
      labels:
        app: workload-app-213
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-214
  namespace: pki-tenant-large-tier-14
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-app-214
  template:
    metadata:
      labels:
        app: workload-app-214
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-215
  namespace: pki-tenant-large-tier-14
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-app-215
  template:
    metadata:
      labels:
        app: workload-app-215
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-216
  namespace: pki-tenant-large-tier-14
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-app-216
  template:
    metadata:
      labels:
        app: workload-app-216
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-217
  namespace: pki-tenant-large-tier-14
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-app-217
  template:
    metadata:
      labels:
        app: workload-app-217
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
