apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-97
  namespace: pki-tenant-large-tier-7
spec:
  replicas: 19
  selector:
    matchLabels:
      app: workload-app-97
  template:
    metadata:
      labels:
        app: workload-app-97
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-98
  namespace: pki-tenant-large-tier-7
spec:
  replicas: 19
  selector:
    matchLabels:
      app: workload-app-98
  template:
    metadata:
      labels:
        app: workload-app-98
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-99
  namespace: pki-tenant-large-tier-7
spec:
  replicas: 19
  selector:
    matchLabels:
      app: workload-app-99
  template:
    metadata:
      labels:
        app: workload-app-99
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-100
  namespace: pki-tenant-large-tier-7
spec:
  replicas: 19
  selector:
    matchLabels:
      app: workload-app-100
  template:
    metadata:
      labels:
        app: workload-app-100
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-101
  namespace: pki-tenant-large-tier-7
spec:
  replicas: 19
  selector:
    matchLabels:
      app: workload-app-101
  template:
    metadata:
      labels:
        app: workload-app-101
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-102
  namespace: pki-tenant-large-tier-7
spec:
  replicas: 19
  selector:
    matchLabels:
      app: workload-app-102
  template:
    metadata:
      labels:
        app: workload-app-102
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-103
  namespace: pki-tenant-large-tier-7
spec:
  replicas: 19
  selector:
    matchLabels:
      app: workload-app-103
  template:
    metadata:
      labels:
        app: workload-app-103
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-104
  namespace: pki-tenant-large-tier-7
spec:
  replicas: 19
  selector:
    matchLabels:
      app: workload-app-104
  template:
    metadata:
      labels:
        app: workload-app-104
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-105
  namespace: pki-tenant-large-tier-7
spec:
  replicas: 19
  selector:
    matchLabels:
      app: workload-app-105
  template:
    metadata:
      labels:
        app: workload-app-105
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-106
  namespace: pki-tenant-large-tier-7
spec:
  replicas: 19
  selector:
    matchLabels:
      app: workload-app-106
  template:
    metadata:
      labels:
        app: workload-app-106
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-107
  namespace: pki-tenant-large-tier-7
spec:
  replicas: 19
  selector:
    matchLabels:
      app: workload-app-107
  template:
    metadata:
      labels:
        app: workload-app-107
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-108
  namespace: pki-tenant-large-tier-7
spec:
  replicas: 19
  selector:
    matchLabels:
      app: workload-app-108
  template:
    metadata:
      labels:
        app: workload-app-108
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-109
  namespace: pki-tenant-large-tier-7
spec:
  replicas: 19
  selector:
    matchLabels:
      app: workload-app-109
  template:
    metadata:
      labels:
        app: workload-app-109
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-110
  namespace: pki-tenant-large-tier-7
spec:
  replicas: 19
  selector:
    matchLabels:
      app: workload-app-110
  template:
    metadata:
      labels:
        app: workload-app-110
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-111
  namespace: pki-tenant-large-tier-7
spec:
  replicas: 19
  selector:
    matchLabels:
      app: workload-app-111
  template:
    metadata:
      labels:
        app: workload-app-111
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-112
  namespace: pki-tenant-large-tier-7
spec:
  replicas: 19
  selector:
    matchLabels:
      app: workload-app-112
  template:
    metadata:
      labels:
        app: workload-app-112
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
