apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-1
  namespace: pki-tenant-large-tier-1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: workload-app-1
  template:
    metadata:
      labels:
        app: workload-app-1
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-2
  namespace: pki-tenant-large-tier-1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: workload-app-2
  template:
    metadata:
      labels:
        app: workload-app-2
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-3
  namespace: pki-tenant-large-tier-1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: workload-app-3
  template:
    metadata:
      labels:
        app: workload-app-3
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-4
  namespace: pki-tenant-large-tier-1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: workload-app-4
  template:
    metadata:
      labels:
        app: workload-app-4
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-5
  namespace: pki-tenant-large-tier-1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: workload-app-5
  template:
    metadata:
      labels:
        app: workload-app-5
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-6
  namespace: pki-tenant-large-tier-1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: workload-app-6
  template:
    metadata:
      labels:
        app: workload-app-6
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-7
  namespace: pki-tenant-large-tier-1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: workload-app-7
  template:
    metadata:
      labels:
        app: workload-app-7
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-8
  namespace: pki-tenant-large-tier-1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: workload-app-8
  template:
    metadata:
      labels:
        app: workload-app-8
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-9
  namespace: pki-tenant-large-tier-1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: workload-app-9
  template:
    metadata:
      labels:
        app: workload-app-9
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-10
  namespace: pki-tenant-large-tier-1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: workload-app-10
  template:
    metadata:
      labels:
        app: workload-app-10
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-11
  namespace: pki-tenant-large-tier-1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: workload-app-11
  template:
    metadata:
      labels:
        app: workload-app-11
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-12
  namespace: pki-tenant-large-tier-1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: workload-app-12
  template:
    metadata:
      labels:
        app: workload-app-12
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-13
  namespace: pki-tenant-large-tier-1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: workload-app-13
  template:
    metadata:
      labels:
        app: workload-app-13
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-14
  namespace: pki-tenant-large-tier-1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: workload-app-14
  template:
    metadata:
      labels:
        app: workload-app-14
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-15
  namespace: pki-tenant-large-tier-1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: workload-app-15
  template:
    metadata:
      labels:
        app: workload-app-15
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-16
  namespace: pki-tenant-large-tier-1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: workload-app-16
  template:
    metadata:
      labels:
        app: workload-app-16
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
