apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-233
  namespace: pki-tenant-large-tier-16
spec:
  replicas: 2
  selector:
    matchLabels:
      app: workload-app-233
  template:
    metadata:
      labels:
        app: workload-app-233
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-234
  namespace: pki-tenant-large-tier-16
spec:
  replicas: 2
  selector:
    matchLabels:
      app: workload-app-234
  template:
    metadata:
      labels:
        app: workload-app-234
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-235
  namespace: pki-tenant-large-tier-16
spec:
  replicas: 2
  selector:
    matchLabels:
      app: workload-app-235
  template:
    metadata:
      labels:
        app: workload-app-235
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-236
  namespace: pki-tenant-large-tier-16
spec:
  replicas: 2
  selector:
    matchLabels:
      app: workload-app-236
  template:
    metadata:
      labels:
        app: workload-app-236
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-237
  namespace: pki-tenant-large-tier-16
spec:
  replicas: 2
  selector:
    matchLabels:
      app: workload-app-237
  template:
    metadata:
      labels:
        app: workload-app-237
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-238
  namespace: pki-tenant-large-tier-16
spec:
  replicas: 2
  selector:
    matchLabels:
      app: workload-app-238
  template:
    metadata:
      labels:
        app: workload-app-238
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-239
  namespace: pki-tenant-large-tier-16
spec:
  replicas: 2
  selector:
    matchLabels:
      app: workload-app-239
  template:
    metadata:
      labels:
        app: workload-app-239
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-240
  namespace: pki-tenant-large-tier-16
spec:
  replicas: 2
  selector:
    matchLabels:
      app: workload-app-240
  template:
    metadata:
      labels:
        app: workload-app-240
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-241
  namespace: pki-tenant-large-tier-16
spec:
  replicas: 2
  selector:
    matchLabels:
      app: workload-app-241
  template:
    metadata:
      labels:
        app: workload-app-241
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-242
  namespace: pki-tenant-large-tier-16
spec:
  replicas: 2
  selector:
    matchLabels:
      app: workload-app-242
  template:
    metadata:
      labels:
        app: workload-app-242
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-243
  namespace: pki-tenant-large-tier-16
spec:
  replicas: 2
  selector:
    matchLabels:
      app: workload-app-243
  template:
    metadata:
      labels:
        app: workload-app-243
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-244
  namespace: pki-tenant-large-tier-16
spec:
  replicas: 2
  selector:
    matchLabels:
      app: workload-app-244
  template:
    metadata:
      labels:
        app: workload-app-244
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-245
  namespace: pki-tenant-large-tier-16
spec:
  replicas: 2
  selector:
    matchLabels:
      app: workload-app-245
  template:
    metadata:
      labels:
        app: workload-app-245
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-246
  namespace: pki-tenant-large-tier-16
spec:
  replicas: 2
  selector:
    matchLabels:
      app: workload-app-246
  template:
    metadata:
      labels:
        app: workload-app-246
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-247
  namespace: pki-tenant-large-tier-16
spec:
  replicas: 2
  selector:
    matchLabels:
      app: workload-app-247
  template:
    metadata:
      labels:
        app: workload-app-247
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
