apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-338
  namespace: pki-tenant-large-tier-23
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-app-338
  template:
    metadata:
      labels:
        app: workload-app-338
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "16Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-339
  namespace: pki-tenant-large-tier-23
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-app-339
  template:
    metadata:
      labels:
        app: workload-app-339
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "16Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-340
  namespace: pki-tenant-large-tier-23
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-app-340
  template:
    metadata:
      labels:
        app: workload-app-340
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "16Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-341
  namespace: pki-tenant-large-tier-23
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-app-341
  template:
    metadata:
      labels:
        app: workload-app-341
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "16Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-342
  namespace: pki-tenant-large-tier-23
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-app-342
  template:
    metadata:
      labels:
        app: workload-app-342
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "16Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-343
  namespace: pki-tenant-large-tier-23
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-app-343
  template:
    metadata:
      labels:
        app: workload-app-343
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "16Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-344
  namespace: pki-tenant-large-tier-23
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-app-344
  template:
    metadata:
      labels:
        app: workload-app-344
    spec:
      containers:
      - name: app
        image: hashicorp/http-echo:latest
        args: ['-text=hello']
        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "16Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-345
  namespace: pki-tenant-large-tier-23
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-app-345
  template:
    metadata:
      labels:
        app: workload-app-345
    spec:
      containers:
      - name: app
        image: hashicorp/http-echo:latest
        args: ['-text=hello']
        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "16Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-346
  namespace: pki-tenant-large-tier-23
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-app-346
  template:
    metadata:
      labels:
        app: workload-app-346
    spec:
      containers:
      - name: app
        image: hashicorp/http-echo:latest
        args: ['-text=hello']
        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "16Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-347
  namespace: pki-tenant-large-tier-23
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-app-347
  template:
    metadata:
      labels:
        app: workload-app-347
    spec:
      containers:
      - name: app
        image: hashicorp/http-echo:latest
        args: ['-text=hello']
        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "16Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-348
  namespace: pki-tenant-large-tier-23
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-app-348
  template:
    metadata:
      labels:
        app: workload-app-348
    spec:
      containers:
      - name: app
        image: hashicorp/http-echo:latest
        args: ['-text=hello']
        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "16Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-349
  namespace: pki-tenant-large-tier-23
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-app-349
  template:
    metadata:
      labels:
        app: workload-app-349
    spec:
      containers:
      - name: app
        image: hashicorp/http-echo:latest
        args: ['-text=hello']
        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "16Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-350
  namespace: pki-tenant-large-tier-23
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-app-350
  template:
    metadata:
      labels:
        app: workload-app-350
    spec:
      containers:
      - name: app
        image: hashicorp/http-echo:latest
        args: ['-text=hello']
        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "16Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-351
  namespace: pki-tenant-large-tier-23
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-app-351
  template:
    metadata:
      labels:
        app: workload-app-351
    spec:
      containers:
      - name: app
        image: hashicorp/http-echo:latest
        args: ['-text=hello']
        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "16Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-352
  namespace: pki-tenant-large-tier-23
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-app-352
  template:
    metadata:
      labels:
        app: workload-app-352
    spec:
      containers:
      - name: app
        image: hashicorp/http-echo:latest
        args: ['-text=hello']
        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "16Mi"
---
