apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-263
  namespace: pki-tenant-large-tier-18
spec:
  replicas: 2
  selector:
    matchLabels:
      app: workload-app-263
  template:
    metadata:
      labels:
        app: workload-app-263
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-264
  namespace: pki-tenant-large-tier-18
spec:
  replicas: 2
  selector:
    matchLabels:
      app: workload-app-264
  template:
    metadata:
      labels:
        app: workload-app-264
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-265
  namespace: pki-tenant-large-tier-18
spec:
  replicas: 2
  selector:
    matchLabels:
      app: workload-app-265
  template:
    metadata:
      labels:
        app: workload-app-265
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-266
  namespace: pki-tenant-large-tier-18
spec:
  replicas: 2
  selector:
    matchLabels:
      app: workload-app-266
  template:
    metadata:
      labels:
        app: workload-app-266
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-267
  namespace: pki-tenant-large-tier-18
spec:
  replicas: 2
  selector:
    matchLabels:
      app: workload-app-267
  template:
    metadata:
      labels:
        app: workload-app-267
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-268
  namespace: pki-tenant-large-tier-18
spec:
  replicas: 2
  selector:
    matchLabels:
      app: workload-app-268
  template:
    metadata:
      labels:
        app: workload-app-268
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-269
  namespace: pki-tenant-large-tier-18
spec:
  replicas: 2
  selector:
    matchLabels:
      app: workload-app-269
  template:
    metadata:
      labels:
        app: workload-app-269
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-270
  namespace: pki-tenant-large-tier-18
spec:
  replicas: 2
  selector:
    matchLabels:
      app: workload-app-270
  template:
    metadata:
      labels:
        app: workload-app-270
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-271
  namespace: pki-tenant-large-tier-18
spec:
  replicas: 2
  selector:
    matchLabels:
      app: workload-app-271
  template:
    metadata:
      labels:
        app: workload-app-271
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-272
  namespace: pki-tenant-large-tier-18
spec:
  replicas: 2
  selector:
    matchLabels:
      app: workload-app-272
  template:
    metadata:
      labels:
        app: workload-app-272
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-273
  namespace: pki-tenant-large-tier-18
spec:
  replicas: 2
  selector:
    matchLabels:
      app: workload-app-273
  template:
    metadata:
      labels:
        app: workload-app-273
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-274
  namespace: pki-tenant-large-tier-18
spec:
  replicas: 2
  selector:
    matchLabels:
      app: workload-app-274
  template:
    metadata:
      labels:
        app: workload-app-274
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-275
  namespace: pki-tenant-large-tier-18
spec:
  replicas: 2
  selector:
    matchLabels:
      app: workload-app-275
  template:
    metadata:
      labels:
        app: workload-app-275
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-276
  namespace: pki-tenant-large-tier-18
spec:
  replicas: 2
  selector:
    matchLabels:
      app: workload-app-276
  template:
    metadata:
      labels:
        app: workload-app-276
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-277
  namespace: pki-tenant-large-tier-18
spec:
  replicas: 2
  selector:
    matchLabels:
      app: workload-app-277
  template:
    metadata:
      labels:
        app: workload-app-277
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
