apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-218
  namespace: pki-tenant-large-tier-15
spec:
  replicas: 19
  selector:
    matchLabels:
      app: workload-app-218
  template:
    metadata:
      labels:
        app: workload-app-218
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "128Mi"
          requests:
            cpu: "50m"
            memory: "64Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-219
  namespace: pki-tenant-large-tier-15
spec:
  replicas: 19
  selector:
    matchLabels:
      app: workload-app-219
  template:
    metadata:
      labels:
        app: workload-app-219
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "128Mi"
          requests:
            cpu: "50m"
            memory: "64Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-220
  namespace: pki-tenant-large-tier-15
spec:
  replicas: 19
  selector:
    matchLabels:
      app: workload-app-220
  template:
    metadata:
      labels:
        app: workload-app-220
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "128Mi"
          requests:
            cpu: "50m"
            memory: "64Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-221
  namespace: pki-tenant-large-tier-15
spec:
  replicas: 19
  selector:
    matchLabels:
      app: workload-app-221
  template:
    metadata:
      labels:
        app: workload-app-221
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "128Mi"
          requests:
            cpu: "50m"
            memory: "64Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-222
  namespace: pki-tenant-large-tier-15
spec:
  replicas: 19
  selector:
    matchLabels:
      app: workload-app-222
  template:
    metadata:
      labels:
        app: workload-app-222
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "128Mi"
          requests:
            cpu: "50m"
            memory: "64Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-223
  namespace: pki-tenant-large-tier-15
spec:
  replicas: 19
  selector:
    matchLabels:
      app: workload-app-223
  template:
    metadata:
      labels:
        app: workload-app-223
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "128Mi"
          requests:
            cpu: "50m"
            memory: "64Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-224
  namespace: pki-tenant-large-tier-15
spec:
  replicas: 19
  selector:
    matchLabels:
      app: workload-app-224
  template:
    metadata:
      labels:
        app: workload-app-224
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "128Mi"
          requests:
            cpu: "50m"
            memory: "64Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-225
  namespace: pki-tenant-large-tier-15
spec:
  replicas: 19
  selector:
    matchLabels:
      app: workload-app-225
  template:
    metadata:
      labels:
        app: workload-app-225
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "128Mi"
          requests:
            cpu: "50m"
            memory: "64Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-226
  namespace: pki-tenant-large-tier-15
spec:
  replicas: 19
  selector:
    matchLabels:
      app: workload-app-226
  template:
    metadata:
      labels:
        app: workload-app-226
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "128Mi"
          requests:
            cpu: "50m"
            memory: "64Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-227
  namespace: pki-tenant-large-tier-15
spec:
  replicas: 19
  selector:
    matchLabels:
      app: workload-app-227
  template:
    metadata:
      labels:
        app: workload-app-227
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "128Mi"
          requests:
            cpu: "50m"
            memory: "64Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-228
  namespace: pki-tenant-large-tier-15
spec:
  replicas: 19
  selector:
    matchLabels:
      app: workload-app-228
  template:
    metadata:
      labels:
        app: workload-app-228
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "128Mi"
          requests:
            cpu: "50m"
            memory: "64Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-229
  namespace: pki-tenant-large-tier-15
spec:
  replicas: 19
  selector:
    matchLabels:
      app: workload-app-229
  template:
    metadata:
      labels:
        app: workload-app-229
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "128Mi"
          requests:
            cpu: "50m"
            memory: "64Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-230
  namespace: pki-tenant-large-tier-15
spec:
  replicas: 19
  selector:
    matchLabels:
      app: workload-app-230
  template:
    metadata:
      labels:
        app: workload-app-230
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "128Mi"
          requests:
            cpu: "50m"
            memory: "64Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-231
  namespace: pki-tenant-large-tier-15
spec:
  replicas: 19
  selector:
    matchLabels:
      app: workload-app-231
  template:
    metadata:
      labels:
        app: workload-app-231
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "128Mi"
          requests:
            cpu: "50m"
            memory: "64Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-232
  namespace: pki-tenant-large-tier-15
spec:
  replicas: 19
  selector:
    matchLabels:
      app: workload-app-232
  template:
    metadata:
      labels:
        app: workload-app-232
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "128Mi"
          requests:
            cpu: "50m"
            memory: "64Mi"
---
