apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-368
  namespace: pki-tenant-large-tier-25
spec:
  replicas: 19
  selector:
    matchLabels:
      app: workload-app-368
  template:
    metadata:
      labels:
        app: workload-app-368
    spec:
      containers:
      - name: app
        image: hashicorp/http-echo:latest
        args: ['-text=hello']
        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "128Mi"
          requests:
            cpu: "50m"
            memory: "64Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-369
  namespace: pki-tenant-large-tier-25
spec:
  replicas: 19
  selector:
    matchLabels:
      app: workload-app-369
  template:
    metadata:
      labels:
        app: workload-app-369
    spec:
      containers:
      - name: app
        image: hashicorp/http-echo:latest
        args: ['-text=hello']
        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "128Mi"
          requests:
            cpu: "50m"
            memory: "64Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-370
  namespace: pki-tenant-large-tier-25
spec:
  replicas: 19
  selector:
    matchLabels:
      app: workload-app-370
  template:
    metadata:
      labels:
        app: workload-app-370
    spec:
      containers:
      - name: app
        image: hashicorp/http-echo:latest
        args: ['-text=hello']
        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "128Mi"
          requests:
            cpu: "50m"
            memory: "64Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-371
  namespace: pki-tenant-large-tier-25
spec:
  replicas: 19
  selector:
    matchLabels:
      app: workload-app-371
  template:
    metadata:
      labels:
        app: workload-app-371
    spec:
      containers:
      - name: app
        image: hashicorp/http-echo:latest
        args: ['-text=hello']
        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "128Mi"
          requests:
            cpu: "50m"
            memory: "64Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-372
  namespace: pki-tenant-large-tier-25
spec:
  replicas: 19
  selector:
    matchLabels:
      app: workload-app-372
  template:
    metadata:
      labels:
        app: workload-app-372
    spec:
      containers:
      - name: app
        image: hashicorp/http-echo:latest
        args: ['-text=hello']
        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "128Mi"
          requests:
            cpu: "50m"
            memory: "64Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-373
  namespace: pki-tenant-large-tier-25
spec:
  replicas: 19
  selector:
    matchLabels:
      app: workload-app-373
  template:
    metadata:
      labels:
        app: workload-app-373
    spec:
      containers:
      - name: app
        image: hashicorp/http-echo:latest
        args: ['-text=hello']
        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "128Mi"
          requests:
            cpu: "50m"
            memory: "64Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-374
  namespace: pki-tenant-large-tier-25
spec:
  replicas: 19
  selector:
    matchLabels:
      app: workload-app-374
  template:
    metadata:
      labels:
        app: workload-app-374
    spec:
      containers:
      - name: app
        image: hashicorp/http-echo:latest
        args: ['-text=hello']
        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "128Mi"
          requests:
            cpu: "50m"
            memory: "64Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-375
  namespace: pki-tenant-large-tier-25
spec:
  replicas: 19
  selector:
    matchLabels:
      app: workload-app-375
  template:
    metadata:
      labels:
        app: workload-app-375
    spec:
      containers:
      - name: app
        image: hashicorp/http-echo:latest
        args: ['-text=hello']
        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "128Mi"
          requests:
            cpu: "50m"
            memory: "64Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-376
  namespace: pki-tenant-large-tier-25
spec:
  replicas: 19
  selector:
    matchLabels:
      app: workload-app-376
  template:
    metadata:
      labels:
        app: workload-app-376
    spec:
      containers:
      - name: app
        image: hashicorp/http-echo:latest
        args: ['-text=hello']
        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "128Mi"
          requests:
            cpu: "50m"
            memory: "64Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-377
  namespace: pki-tenant-large-tier-25
spec:
  replicas: 19
  selector:
    matchLabels:
      app: workload-app-377
  template:
    metadata:
      labels:
        app: workload-app-377
    spec:
      containers:
      - name: app
        image: hashicorp/http-echo:latest
        args: ['-text=hello']
        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "128Mi"
          requests:
            cpu: "50m"
            memory: "64Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-378
  namespace: pki-tenant-large-tier-25
spec:
  replicas: 19
  selector:
    matchLabels:
      app: workload-app-378
  template:
    metadata:
      labels:
        app: workload-app-378
    spec:
      containers:
      - name: app
        image: hashicorp/http-echo:latest
        args: ['-text=hello']
        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "128Mi"
          requests:
            cpu: "50m"
            memory: "64Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-379
  namespace: pki-tenant-large-tier-25
spec:
  replicas: 19
  selector:
    matchLabels:
      app: workload-app-379
  template:
    metadata:
      labels:
        app: workload-app-379
    spec:
      containers:
      - name: app
        image: hashicorp/http-echo:latest
        args: ['-text=hello']
        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "128Mi"
          requests:
            cpu: "50m"
            memory: "64Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-380
  namespace: pki-tenant-large-tier-25
spec:
  replicas: 19
  selector:
    matchLabels:
      app: workload-app-380
  template:
    metadata:
      labels:
        app: workload-app-380
    spec:
      containers:
      - name: app
        image: hashicorp/http-echo:latest
        args: ['-text=hello']
        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "128Mi"
          requests:
            cpu: "50m"
            memory: "64Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-381
  namespace: pki-tenant-large-tier-25
spec:
  replicas: 19
  selector:
    matchLabels:
      app: workload-app-381
  template:
    metadata:
      labels:
        app: workload-app-381
    spec:
      containers:
      - name: app
        image: hashicorp/http-echo:latest
        args: ['-text=hello']
        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "128Mi"
          requests:
            cpu: "50m"
            memory: "64Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-382
  namespace: pki-tenant-large-tier-25
spec:
  replicas: 19
  selector:
    matchLabels:
      app: workload-app-382
  template:
    metadata:
      labels:
        app: workload-app-382
    spec:
      containers:
      - name: app
        image: hashicorp/http-echo:latest
        args: ['-text=hello']
        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "128Mi"
          requests:
            cpu: "50m"
            memory: "64Mi"
---
