apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-81
  namespace: pki-tenant-large-tier-6
spec:
  replicas: 2
  selector:
    matchLabels:
      app: workload-app-81
  template:
    metadata:
      labels:
        app: workload-app-81
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-82
  namespace: pki-tenant-large-tier-6
spec:
  replicas: 2
  selector:
    matchLabels:
      app: workload-app-82
  template:
    metadata:
      labels:
        app: workload-app-82
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-83
  namespace: pki-tenant-large-tier-6
spec:
  replicas: 2
  selector:
    matchLabels:
      app: workload-app-83
  template:
    metadata:
      labels:
        app: workload-app-83
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-84
  namespace: pki-tenant-large-tier-6
spec:
  replicas: 2
  selector:
    matchLabels:
      app: workload-app-84
  template:
    metadata:
      labels:
        app: workload-app-84
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-85
  namespace: pki-tenant-large-tier-6
spec:
  replicas: 2
  selector:
    matchLabels:
      app: workload-app-85
  template:
    metadata:
      labels:
        app: workload-app-85
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-86
  namespace: pki-tenant-large-tier-6
spec:
  replicas: 2
  selector:
    matchLabels:
      app: workload-app-86
  template:
    metadata:
      labels:
        app: workload-app-86
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-87
  namespace: pki-tenant-large-tier-6
spec:
  replicas: 2
  selector:
    matchLabels:
      app: workload-app-87
  template:
    metadata:
      labels:
        app: workload-app-87
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-88
  namespace: pki-tenant-large-tier-6
spec:
  replicas: 2
  selector:
    matchLabels:
      app: workload-app-88
  template:
    metadata:
      labels:
        app: workload-app-88
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-89
  namespace: pki-tenant-large-tier-6
spec:
  replicas: 2
  selector:
    matchLabels:
      app: workload-app-89
  template:
    metadata:
      labels:
        app: workload-app-89
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-90
  namespace: pki-tenant-large-tier-6
spec:
  replicas: 2
  selector:
    matchLabels:
      app: workload-app-90
  template:
    metadata:
      labels:
        app: workload-app-90
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-91
  namespace: pki-tenant-large-tier-6
spec:
  replicas: 2
  selector:
    matchLabels:
      app: workload-app-91
  template:
    metadata:
      labels:
        app: workload-app-91
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-92
  namespace: pki-tenant-large-tier-6
spec:
  replicas: 2
  selector:
    matchLabels:
      app: workload-app-92
  template:
    metadata:
      labels:
        app: workload-app-92
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-93
  namespace: pki-tenant-large-tier-6
spec:
  replicas: 2
  selector:
    matchLabels:
      app: workload-app-93
  template:
    metadata:
      labels:
        app: workload-app-93
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-94
  namespace: pki-tenant-large-tier-6
spec:
  replicas: 2
  selector:
    matchLabels:
      app: workload-app-94
  template:
    metadata:
      labels:
        app: workload-app-94
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-95
  namespace: pki-tenant-large-tier-6
spec:
  replicas: 2
  selector:
    matchLabels:
      app: workload-app-95
  template:
    metadata:
      labels:
        app: workload-app-95
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-96
  namespace: pki-tenant-large-tier-6
spec:
  replicas: 2
  selector:
    matchLabels:
      app: workload-app-96
  template:
    metadata:
      labels:
        app: workload-app-96
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
