apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-353
  namespace: pki-tenant-large-tier-24
spec:
  replicas: 19
  selector:
    matchLabels:
      app: workload-app-353
  template:
    metadata:
      labels:
        app: workload-app-353
    spec:
      containers:
      - name: app
        image: hashicorp/http-echo:latest
        args: ['-text=hello']
        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-354
  namespace: pki-tenant-large-tier-24
spec:
  replicas: 19
  selector:
    matchLabels:
      app: workload-app-354
  template:
    metadata:
      labels:
        app: workload-app-354
    spec:
      containers:
      - name: app
        image: hashicorp/http-echo:latest
        args: ['-text=hello']
        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-355
  namespace: pki-tenant-large-tier-24
spec:
  replicas: 19
  selector:
    matchLabels:
      app: workload-app-355
  template:
    metadata:
      labels:
        app: workload-app-355
    spec:
      containers:
      - name: app
        image: hashicorp/http-echo:latest
        args: ['-text=hello']
        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-356
  namespace: pki-tenant-large-tier-24
spec:
  replicas: 19
  selector:
    matchLabels:
      app: workload-app-356
  template:
    metadata:
      labels:
        app: workload-app-356
    spec:
      containers:
      - name: app
        image: hashicorp/http-echo:latest
        args: ['-text=hello']
        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-357
  namespace: pki-tenant-large-tier-24
spec:
  replicas: 19
  selector:
    matchLabels:
      app: workload-app-357
  template:
    metadata:
      labels:
        app: workload-app-357
    spec:
      containers:
      - name: app
        image: hashicorp/http-echo:latest
        args: ['-text=hello']
        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-358
  namespace: pki-tenant-large-tier-24
spec:
  replicas: 19
  selector:
    matchLabels:
      app: workload-app-358
  template:
    metadata:
      labels:
        app: workload-app-358
    spec:
      containers:
      - name: app
        image: hashicorp/http-echo:latest
        args: ['-text=hello']
        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-359
  namespace: pki-tenant-large-tier-24
spec:
  replicas: 19
  selector:
    matchLabels:
      app: workload-app-359
  template:
    metadata:
      labels:
        app: workload-app-359
    spec:
      containers:
      - name: app
        image: hashicorp/http-echo:latest
        args: ['-text=hello']
        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-360
  namespace: pki-tenant-large-tier-24
spec:
  replicas: 19
  selector:
    matchLabels:
      app: workload-app-360
  template:
    metadata:
      labels:
        app: workload-app-360
    spec:
      containers:
      - name: app
        image: hashicorp/http-echo:latest
        args: ['-text=hello']
        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-361
  namespace: pki-tenant-large-tier-24
spec:
  replicas: 19
  selector:
    matchLabels:
      app: workload-app-361
  template:
    metadata:
      labels:
        app: workload-app-361
    spec:
      containers:
      - name: app
        image: hashicorp/http-echo:latest
        args: ['-text=hello']
        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-362
  namespace: pki-tenant-large-tier-24
spec:
  replicas: 19
  selector:
    matchLabels:
      app: workload-app-362
  template:
    metadata:
      labels:
        app: workload-app-362
    spec:
      containers:
      - name: app
        image: hashicorp/http-echo:latest
        args: ['-text=hello']
        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-363
  namespace: pki-tenant-large-tier-24
spec:
  replicas: 19
  selector:
    matchLabels:
      app: workload-app-363
  template:
    metadata:
      labels:
        app: workload-app-363
    spec:
      containers:
      - name: app
        image: hashicorp/http-echo:latest
        args: ['-text=hello']
        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-364
  namespace: pki-tenant-large-tier-24
spec:
  replicas: 19
  selector:
    matchLabels:
      app: workload-app-364
  template:
    metadata:
      labels:
        app: workload-app-364
    spec:
      containers:
      - name: app
        image: hashicorp/http-echo:latest
        args: ['-text=hello']
        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-365
  namespace: pki-tenant-large-tier-24
spec:
  replicas: 19
  selector:
    matchLabels:
      app: workload-app-365
  template:
    metadata:
      labels:
        app: workload-app-365
    spec:
      containers:
      - name: app
        image: hashicorp/http-echo:latest
        args: ['-text=hello']
        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-366
  namespace: pki-tenant-large-tier-24
spec:
  replicas: 19
  selector:
    matchLabels:
      app: workload-app-366
  template:
    metadata:
      labels:
        app: workload-app-366
    spec:
      containers:
      - name: app
        image: hashicorp/http-echo:latest
        args: ['-text=hello']
        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-367
  namespace: pki-tenant-large-tier-24
spec:
  replicas: 19
  selector:
    matchLabels:
      app: workload-app-367
  template:
    metadata:
      labels:
        app: workload-app-367
    spec:
      containers:
      - name: app
        image: hashicorp/http-echo:latest
        args: ['-text=hello']
        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
