apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-248
  namespace: pki-tenant-large-tier-17
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-app-248
  template:
    metadata:
      labels:
        app: workload-app-248
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-249
  namespace: pki-tenant-large-tier-17
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-app-249
  template:
    metadata:
      labels:
        app: workload-app-249
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-250
  namespace: pki-tenant-large-tier-17
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-app-250
  template:
    metadata:
      labels:
        app: workload-app-250
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-251
  namespace: pki-tenant-large-tier-17
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-app-251
  template:
    metadata:
      labels:
        app: workload-app-251
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-252
  namespace: pki-tenant-large-tier-17
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-app-252
  template:
    metadata:
      labels:
        app: workload-app-252
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-253
  namespace: pki-tenant-large-tier-17
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-app-253
  template:
    metadata:
      labels:
        app: workload-app-253
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-254
  namespace: pki-tenant-large-tier-17
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-app-254
  template:
    metadata:
      labels:
        app: workload-app-254
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-255
  namespace: pki-tenant-large-tier-17
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-app-255
  template:
    metadata:
      labels:
        app: workload-app-255
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-256
  namespace: pki-tenant-large-tier-17
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-app-256
  template:
    metadata:
      labels:
        app: workload-app-256
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-257
  namespace: pki-tenant-large-tier-17
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-app-257
  template:
    metadata:
      labels:
        app: workload-app-257
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-258
  namespace: pki-tenant-large-tier-17
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-app-258
  template:
    metadata:
      labels:
        app: workload-app-258
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-259
  namespace: pki-tenant-large-tier-17
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-app-259
  template:
    metadata:
      labels:
        app: workload-app-259
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-260
  namespace: pki-tenant-large-tier-17
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-app-260
  template:
    metadata:
      labels:
        app: workload-app-260
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-261
  namespace: pki-tenant-large-tier-17
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-app-261
  template:
    metadata:
      labels:
        app: workload-app-261
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-262
  namespace: pki-tenant-large-tier-17
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-app-262
  template:
    metadata:
      labels:
        app: workload-app-262
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
