apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-188
  namespace: pki-tenant-large-tier-13
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-app-188
  template:
    metadata:
      labels:
        app: workload-app-188
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "16Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-189
  namespace: pki-tenant-large-tier-13
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-app-189
  template:
    metadata:
      labels:
        app: workload-app-189
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "16Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-190
  namespace: pki-tenant-large-tier-13
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-app-190
  template:
    metadata:
      labels:
        app: workload-app-190
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "16Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-191
  namespace: pki-tenant-large-tier-13
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-app-191
  template:
    metadata:
      labels:
        app: workload-app-191
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "16Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-192
  namespace: pki-tenant-large-tier-13
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-app-192
  template:
    metadata:
      labels:
        app: workload-app-192
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "16Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-193
  namespace: pki-tenant-large-tier-13
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-app-193
  template:
    metadata:
      labels:
        app: workload-app-193
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "16Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-194
  namespace: pki-tenant-large-tier-13
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-app-194
  template:
    metadata:
      labels:
        app: workload-app-194
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "16Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-195
  namespace: pki-tenant-large-tier-13
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-app-195
  template:
    metadata:
      labels:
        app: workload-app-195
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "16Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-196
  namespace: pki-tenant-large-tier-13
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-app-196
  template:
    metadata:
      labels:
        app: workload-app-196
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "16Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-197
  namespace: pki-tenant-large-tier-13
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-app-197
  template:
    metadata:
      labels:
        app: workload-app-197
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "16Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-198
  namespace: pki-tenant-large-tier-13
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-app-198
  template:
    metadata:
      labels:
        app: workload-app-198
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "16Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-199
  namespace: pki-tenant-large-tier-13
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-app-199
  template:
    metadata:
      labels:
        app: workload-app-199
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "16Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-200
  namespace: pki-tenant-large-tier-13
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-app-200
  template:
    metadata:
      labels:
        app: workload-app-200
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "16Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-201
  namespace: pki-tenant-large-tier-13
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-app-201
  template:
    metadata:
      labels:
        app: workload-app-201
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "16Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-202
  namespace: pki-tenant-large-tier-13
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-app-202
  template:
    metadata:
      labels:
        app: workload-app-202
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "16Mi"
---
