apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-38
  namespace: pki-tenant-medium-tier-6
spec:
  replicas: 11
  selector:
    matchLabels:
      app: workload-app-38
  template:
    metadata:
      labels:
        app: workload-app-38
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "10m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-39
  namespace: pki-tenant-medium-tier-6
spec:
  replicas: 11
  selector:
    matchLabels:
      app: workload-app-39
  template:
    metadata:
      labels:
        app: workload-app-39
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "10m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-40
  namespace: pki-tenant-medium-tier-6
spec:
  replicas: 11
  selector:
    matchLabels:
      app: workload-app-40
  template:
    metadata:
      labels:
        app: workload-app-40
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "10m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-41
  namespace: pki-tenant-medium-tier-6
spec:
  replicas: 11
  selector:
    matchLabels:
      app: workload-app-41
  template:
    metadata:
      labels:
        app: workload-app-41
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "10m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-42
  namespace: pki-tenant-medium-tier-6
spec:
  replicas: 11
  selector:
    matchLabels:
      app: workload-app-42
  template:
    metadata:
      labels:
        app: workload-app-42
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "10m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-43
  namespace: pki-tenant-medium-tier-6
spec:
  replicas: 11
  selector:
    matchLabels:
      app: workload-app-43
  template:
    metadata:
      labels:
        app: workload-app-43
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "10m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-44
  namespace: pki-tenant-medium-tier-6
spec:
  replicas: 11
  selector:
    matchLabels:
      app: workload-app-44
  template:
    metadata:
      labels:
        app: workload-app-44
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "10m"
            memory: "32Mi"
---
