apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-113
  namespace: pki-tenant-large-tier-8
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-app-113
  template:
    metadata:
      labels:
        app: workload-app-113
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "16Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-114
  namespace: pki-tenant-large-tier-8
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-app-114
  template:
    metadata:
      labels:
        app: workload-app-114
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "16Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-115
  namespace: pki-tenant-large-tier-8
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-app-115
  template:
    metadata:
      labels:
        app: workload-app-115
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "16Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-116
  namespace: pki-tenant-large-tier-8
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-app-116
  template:
    metadata:
      labels:
        app: workload-app-116
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "16Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-117
  namespace: pki-tenant-large-tier-8
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-app-117
  template:
    metadata:
      labels:
        app: workload-app-117
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "16Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-118
  namespace: pki-tenant-large-tier-8
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-app-118
  template:
    metadata:
      labels:
        app: workload-app-118
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "16Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-119
  namespace: pki-tenant-large-tier-8
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-app-119
  template:
    metadata:
      labels:
        app: workload-app-119
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "16Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-120
  namespace: pki-tenant-large-tier-8
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-app-120
  template:
    metadata:
      labels:
        app: workload-app-120
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "16Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-121
  namespace: pki-tenant-large-tier-8
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-app-121
  template:
    metadata:
      labels:
        app: workload-app-121
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "16Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-122
  namespace: pki-tenant-large-tier-8
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-app-122
  template:
    metadata:
      labels:
        app: workload-app-122
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "16Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-123
  namespace: pki-tenant-large-tier-8
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-app-123
  template:
    metadata:
      labels:
        app: workload-app-123
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "16Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-124
  namespace: pki-tenant-large-tier-8
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-app-124
  template:
    metadata:
      labels:
        app: workload-app-124
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "16Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-125
  namespace: pki-tenant-large-tier-8
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-app-125
  template:
    metadata:
      labels:
        app: workload-app-125
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "16Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-126
  namespace: pki-tenant-large-tier-8
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-app-126
  template:
    metadata:
      labels:
        app: workload-app-126
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "16Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-127
  namespace: pki-tenant-large-tier-8
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-app-127
  template:
    metadata:
      labels:
        app: workload-app-127
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "16Mi"
---
