apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-158
  namespace: pki-tenant-large-tier-11
spec:
  replicas: 2
  selector:
    matchLabels:
      app: workload-app-158
  template:
    metadata:
      labels:
        app: workload-app-158
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-159
  namespace: pki-tenant-large-tier-11
spec:
  replicas: 2
  selector:
    matchLabels:
      app: workload-app-159
  template:
    metadata:
      labels:
        app: workload-app-159
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-160
  namespace: pki-tenant-large-tier-11
spec:
  replicas: 2
  selector:
    matchLabels:
      app: workload-app-160
  template:
    metadata:
      labels:
        app: workload-app-160
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-161
  namespace: pki-tenant-large-tier-11
spec:
  replicas: 2
  selector:
    matchLabels:
      app: workload-app-161
  template:
    metadata:
      labels:
        app: workload-app-161
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-162
  namespace: pki-tenant-large-tier-11
spec:
  replicas: 2
  selector:
    matchLabels:
      app: workload-app-162
  template:
    metadata:
      labels:
        app: workload-app-162
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-163
  namespace: pki-tenant-large-tier-11
spec:
  replicas: 2
  selector:
    matchLabels:
      app: workload-app-163
  template:
    metadata:
      labels:
        app: workload-app-163
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-164
  namespace: pki-tenant-large-tier-11
spec:
  replicas: 2
  selector:
    matchLabels:
      app: workload-app-164
  template:
    metadata:
      labels:
        app: workload-app-164
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-165
  namespace: pki-tenant-large-tier-11
spec:
  replicas: 2
  selector:
    matchLabels:
      app: workload-app-165
  template:
    metadata:
      labels:
        app: workload-app-165
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-166
  namespace: pki-tenant-large-tier-11
spec:
  replicas: 2
  selector:
    matchLabels:
      app: workload-app-166
  template:
    metadata:
      labels:
        app: workload-app-166
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-167
  namespace: pki-tenant-large-tier-11
spec:
  replicas: 2
  selector:
    matchLabels:
      app: workload-app-167
  template:
    metadata:
      labels:
        app: workload-app-167
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-168
  namespace: pki-tenant-large-tier-11
spec:
  replicas: 2
  selector:
    matchLabels:
      app: workload-app-168
  template:
    metadata:
      labels:
        app: workload-app-168
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-169
  namespace: pki-tenant-large-tier-11
spec:
  replicas: 2
  selector:
    matchLabels:
      app: workload-app-169
  template:
    metadata:
      labels:
        app: workload-app-169
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-170
  namespace: pki-tenant-large-tier-11
spec:
  replicas: 2
  selector:
    matchLabels:
      app: workload-app-170
  template:
    metadata:
      labels:
        app: workload-app-170
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-171
  namespace: pki-tenant-large-tier-11
spec:
  replicas: 2
  selector:
    matchLabels:
      app: workload-app-171
  template:
    metadata:
      labels:
        app: workload-app-171
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-172
  namespace: pki-tenant-large-tier-11
spec:
  replicas: 2
  selector:
    matchLabels:
      app: workload-app-172
  template:
    metadata:
      labels:
        app: workload-app-172
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "2m"
            memory: "32Mi"
---
