apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-49
  namespace: pki-tenant-large-tier-4
spec:
  replicas: 19
  selector:
    matchLabels:
      app: workload-app-49
  template:
    metadata:
      labels:
        app: workload-app-49
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "128Mi"
          requests:
            cpu: "50m"
            memory: "64Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-50
  namespace: pki-tenant-large-tier-4
spec:
  replicas: 19
  selector:
    matchLabels:
      app: workload-app-50
  template:
    metadata:
      labels:
        app: workload-app-50
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "128Mi"
          requests:
            cpu: "50m"
            memory: "64Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-51
  namespace: pki-tenant-large-tier-4
spec:
  replicas: 19
  selector:
    matchLabels:
      app: workload-app-51
  template:
    metadata:
      labels:
        app: workload-app-51
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "128Mi"
          requests:
            cpu: "50m"
            memory: "64Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-52
  namespace: pki-tenant-large-tier-4
spec:
  replicas: 19
  selector:
    matchLabels:
      app: workload-app-52
  template:
    metadata:
      labels:
        app: workload-app-52
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "128Mi"
          requests:
            cpu: "50m"
            memory: "64Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-53
  namespace: pki-tenant-large-tier-4
spec:
  replicas: 19
  selector:
    matchLabels:
      app: workload-app-53
  template:
    metadata:
      labels:
        app: workload-app-53
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "128Mi"
          requests:
            cpu: "50m"
            memory: "64Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-54
  namespace: pki-tenant-large-tier-4
spec:
  replicas: 19
  selector:
    matchLabels:
      app: workload-app-54
  template:
    metadata:
      labels:
        app: workload-app-54
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "128Mi"
          requests:
            cpu: "50m"
            memory: "64Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-55
  namespace: pki-tenant-large-tier-4
spec:
  replicas: 19
  selector:
    matchLabels:
      app: workload-app-55
  template:
    metadata:
      labels:
        app: workload-app-55
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "128Mi"
          requests:
            cpu: "50m"
            memory: "64Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-56
  namespace: pki-tenant-large-tier-4
spec:
  replicas: 19
  selector:
    matchLabels:
      app: workload-app-56
  template:
    metadata:
      labels:
        app: workload-app-56
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "128Mi"
          requests:
            cpu: "50m"
            memory: "64Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-57
  namespace: pki-tenant-large-tier-4
spec:
  replicas: 19
  selector:
    matchLabels:
      app: workload-app-57
  template:
    metadata:
      labels:
        app: workload-app-57
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "128Mi"
          requests:
            cpu: "50m"
            memory: "64Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-58
  namespace: pki-tenant-large-tier-4
spec:
  replicas: 19
  selector:
    matchLabels:
      app: workload-app-58
  template:
    metadata:
      labels:
        app: workload-app-58
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "128Mi"
          requests:
            cpu: "50m"
            memory: "64Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-59
  namespace: pki-tenant-large-tier-4
spec:
  replicas: 19
  selector:
    matchLabels:
      app: workload-app-59
  template:
    metadata:
      labels:
        app: workload-app-59
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "128Mi"
          requests:
            cpu: "50m"
            memory: "64Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-60
  namespace: pki-tenant-large-tier-4
spec:
  replicas: 19
  selector:
    matchLabels:
      app: workload-app-60
  template:
    metadata:
      labels:
        app: workload-app-60
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "128Mi"
          requests:
            cpu: "50m"
            memory: "64Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-61
  namespace: pki-tenant-large-tier-4
spec:
  replicas: 19
  selector:
    matchLabels:
      app: workload-app-61
  template:
    metadata:
      labels:
        app: workload-app-61
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "128Mi"
          requests:
            cpu: "50m"
            memory: "64Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-62
  namespace: pki-tenant-large-tier-4
spec:
  replicas: 19
  selector:
    matchLabels:
      app: workload-app-62
  template:
    metadata:
      labels:
        app: workload-app-62
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "128Mi"
          requests:
            cpu: "50m"
            memory: "64Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-63
  namespace: pki-tenant-large-tier-4
spec:
  replicas: 19
  selector:
    matchLabels:
      app: workload-app-63
  template:
    metadata:
      labels:
        app: workload-app-63
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "128Mi"
          requests:
            cpu: "50m"
            memory: "64Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-app-64
  namespace: pki-tenant-large-tier-4
spec:
  replicas: 19
  selector:
    matchLabels:
      app: workload-app-64
  template:
    metadata:
      labels:
        app: workload-app-64
    spec:
      containers:
      - name: app
        image: nginx:latest

        envFrom:
        - configMapRef:
            name: demo-cm-1
        - secretRef:
            name: demo-secret-1
        resources:
          limits:
            cpu: "100m"
            memory: "128Mi"
          requests:
            cpu: "50m"
            memory: "64Mi"
---
